### ISSUE TITLE
Get rid of the `GuiStone` class

### ISSUE THREAD

**Issue by peiva-git** [peiva-git/SDM_project#113]
By using the `setUserObject()` method, we may get rid of the `GuiStone` class altogether

**Comment by manuelkoso** [comment]
Yes, you are right.

**Comment by manuelkoso** [comment]
Now I have realized, how do you implement the `getPiece()` method without the `GuiStone` class?

**Comment by peiva-git** [comment]
I was thinking by returning an `Image`. The actor's color should be available with the `getColor()` method, so it may work even without using `getUserObject()`

**Comment by manuelkoso** [comment]
But the `Image` class doesn't extends `Stone`. For example, how do you use the `FreedomPointsCounter`?

**Comment by manuelkoso** [comment]
Ah ok, maybe I got it. Something like that?
 
```java
    @Override
    @SuppressWarnings("unchecked")
    public @Nullable GuiStone getPiece(@NotNull Position position) throws InvalidPositionException {
        for(Cell<Actor> cell : getCells()) {
            if(getPositionFromTile(cell).equals(position)) {
                Group tileAndPiece = (Group) cell.getActor();
                if (tileAndPiece.getChildren().size < 2) {
                    return null;
                } else {
                    return new Stone((Color) tileAndPiece.getUserObject());
                }
            }
        }
        throw new InvalidPositionException("Invalid position, no matching cell found");
    }
```

**Comment by peiva-git** [comment]
I thought you removed the `extends Stone` part from the `Board` interface. If you did, we could simply use a `Board<Actor>` as the GUI board

**Comment by manuelkoso** [comment]
I don't know how would you do this. You can create a pull request in case.

**Comment by peiva-git** [comment]
Won't try this out, one solution might be to implement `Stone` as an interface and then implement it in an `Actor` subclass and a `TerminalStone` class, but I suspect this wouldn't improve the code quality anyway

**Comment by peiva-git** [comment]
I gave it a try, it seems to me that this issue requires more effort than it's actually worth it. In particular, a `GuiChecker` would basically be the same as an `Image`, no other more specific features are added since the `getColor()` method behaves exaclty the same as in the `Actor` class.
