### ISSUE TITLE
Improve unit testing

### ISSUE THREAD

**Issue by peiva-git** [peiva-git/SDM_project#25]
Improve tests by checking the following:
1. There should be a test for each class method
2. For each method, test:
    1. One correct input
    2. One wrong input
    3. Every border case
    4. Test for exceptions thrown

**Comment by manuelkoso** [comment]
Please create a separate branch and create a pull request, so that I can understand/review what you are doing.

**Comment by peiva-git** [comment]
I'll create a pull request for the BoardTests class, which had the largest amount of refactoring done on

**Comment by manuelkoso** [comment]
Even for small changes we have to use branches. If both of us work on the master branch (at the same time), it can become a mess.
