### ISSUE TITLE
Replace Position occurences with (row, column) in method parameters

### ISSUE THREAD

**Issue by peiva-git** [peiva-git/SDM_project#37]
Instead of using a new Position instance every time we call a method, create a new instance inside the method (or perhaps some other solution might work as well)

**Comment by manuelkoso** [comment]
I will do it after #48

**Comment by manuelkoso** [comment]
I realized that in some cases is useful to have as argument `Position` (for example when we get the user input). So, I don't know if it is convenient to replace all the methods. I tried to double them (one version with `Position` as argument and the other version with `int rowIndex` and `int colIndex` as arguments), but I don't know if it is the right choice. Let me know what you think.

**Comment by manuelkoso** [comment]
Yes, ok, but what about:
```java
Position chosenPosition = userInput.getPosition();
            if (isPositionInsideBoardRange(chosenPosition)) { ...
```
or when we iterate over the board:
```java
for (Position currentPosition : board) {
            if (board.getStone(currentPosition) == null) continue;
            checkAllFreedomLinesFrom(currentPosition);
        }
```
These are public methods.

**Comment by peiva-git** [comment]
The first public method returns a `Position` and has no arguments, so that's fine, while the second is actually `private`, what's the issue here?

**Comment by manuelkoso** [comment]
My point is that also for public methods can be useful to have `Position` as argument

**Comment by peiva-git** [comment]
The `getStone` method is a perfect example of why I would do this refactoring: instead of creating a new `Position` each time the method is invoked, wouldn't it be better to create the `Position` inside the method with the provided `row` and `column` arguments?

**Comment by manuelkoso** [comment]
But here the iterator gives us a `Position` object

**Comment by peiva-git** [comment]
Perhaps an interesting solution could be to have a static method in the `Position` class to generate new `Position` instances, similar to the `Integer.valueOf()` method. As per the official documentation, an advantage of this approach would be that we can cache recently used values. The `Integer` code is available [here](https://github.com/openjdk/jdk/blob/014c658708f489e029592ea1e986812cf7c253b8/src/java.base/share/classes/java/lang/Integer.java#L1067)

**Comment by manuelkoso** [comment]
Good idea! I will implement it
