### ISSUE TITLE
Get rid of the `Cell` and `Move` classes

### ISSUE THREAD

**Issue by peiva-git** [peiva-git/SDM_project#47]
These two classes may actually be useful only for the internal implementation of `Board` and `Game` classes respectively

**Comment by manuelkoso** [comment]
The `Cell` class can be useful if we are going to implement games where it is important to know the colors of the cells (like Chess). So I would leave it, instead we can put it into the `Board` class, as you said. 
NOTE: in the case of Chess, I think that the iterator has to return also the color of the cell. So, I don't know if we have made the right decision by removing the `Cell` from the iterator

**Comment by peiva-git** [comment]
Why is cell color important in a chess game? The pieces move according to their own constraints, regardless of the cell color. As far as I know, the cell color is not important, only the cell coordinates (or position) are

**Comment by manuelkoso** [comment]
I thought about the bishop, but, yes, you can consider only the directions/positions. My mistake, I was wondering whether we had lost generality by removing the `Cell` class. So, ok, let's leave the iterator only with the `Position`.

**Comment by peiva-git** [comment]
I'd like to try and address this issue with some refactoring, then you could review it and let me know what you think

**Comment by manuelkoso** [comment]
Ok super
