### ISSUE TITLE
Add branch protection rules 

### ISSUE THREAD

**Issue by manuelkoso** [peiva-git/SDM_project#5]
Follow [Managing a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule )

Add the following rules:
1. Require a pull request before merging 
2. Require approvals

**Comment by peiva-git** [comment]
Branch protection rule correctly added, pull request approval required before merging
